version: "3.8"

services:
  consul-server:
    container_name: consul-server
    image: hashicorp/consul:1.14
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8300:8300"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge